import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ConnectionWindow } from '../components/ConnectionWindow';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
		<h1 className={styles.title}>
          Welcome to Createst
        </h1>
		
		<div className={styles.container}>
		  <main className={styles.main}>
			<ConnectButton />
			<ConnectionWindow />
		  </main>
		</div>
        

        <div className={styles.grid}>
        </div>


      </main>
    </div>
  );
};

export default Home;
